<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>plg</string>
		<string>prolog</string>
		<string>pl</string>
		<string>pr</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(%\s*region \w*)|([a-z]\w*.*:- ?)</string>
	<key>foldingStopMarker</key>
	<string>(%\s*end(\s*region)?)|(?=\.)</string>
	<key>name</key>
	<string>Prolog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#basic_fact</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fact</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>atom</key>
		<dict>
			<key>name</key>
			<string>meta.atom.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[a-z][a-zA-Z0-9_]*\b</string>
					<key>name</key>
					<string>constant.other.atom.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?\d+(\.\d+)?</string>
					<key>name</key>
					<string>constant.numeric.prolog</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>basic_elem</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtins</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>basic_fact</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fact.basic.prolog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.fact.basic.prolog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-z]\w*)(\.)</string>
			<key>name</key>
			<string>meta.fact.basic.prolog</string>
		</dict>
		<key>builtins</key>
		<dict>
			<key>match</key>
			<string>\b(?x:
						abolish|abort|ancestors|arg|ascii|assert[az]|
						atom(ic)?|body|char|close|conc|concat|consult|
						define|definition|dynamic|dump|fail|file|free|
						free_proc|functor|getc|goal|halt|head|head|integer|
						length|listing|match_args|member|next_clause|nl|
						nonvar|nth|number|cvars|nvars|offset|op|
						print?|prompt|putc|quoted|ratom|read|redefine|
						rename|retract(all)?|see|seeing|seen|skip|spy|
						statistics|system|tab|tell|telling|term|
						time|told|univ|unlink_clause|unspy_predicate|
						var|write
					)\b</string>
			<key>name</key>
			<string>support.function.builtin.prolog</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>meta.comment.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.prolog</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(%).*$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.prolog</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.prolog</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|yes|no)\b</string>
			<key>name</key>
			<string>constant.language.prolog</string>
		</dict>
		<key>directive</key>
		<dict>
			<key>begin</key>
			<string>:-</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.directive.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.directive.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
			</array>
		</dict>
		<key>expr</key>
		<dict>
			<key>name</key>
			<string>meta.expression.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.expression.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expr</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>!</string>
					<key>name</key>
					<string>keyword.control.cutoff.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.control.and.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.control.or.prolog</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#basic_elem</string>
				</dict>
			</array>
		</dict>
		<key>fact</key>
		<dict>
			<key>begin</key>
			<string>([a-z]\w*)(\()(?!.*:-)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fact.prolog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.begin.fact.parameters.prolog</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.fact.parameters.prolog</string>
			<key>end</key>
			<string>(\))(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.fact.parameters.prolog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.fact.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.fact.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\[(?=.*\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.begin.list.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.list.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.list.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.list.prolog</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.concat.list.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\])</string>
					<key>name</key>
					<string>meta.list.concat.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#basic_elem</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#basic_elem</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>(\\\+|\bnot\b|\bis\b|-&gt;|[&gt;&lt;]|[&gt;&lt;\\:=]?=|(=\\|\\=)=)</string>
			<key>name</key>
			<string>keyword.operator.prolog</string>
		</dict>
		<key>parameter</key>
		<dict>
			<key>name</key>
			<string>meta.parameter.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b_\b</string>
					<key>name</key>
					<string>variable.language.anonymous.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Z_]\w*\b</string>
					<key>name</key>
					<string>variable.parameter.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.parameters.prolog</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#basic_elem</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s]</string>
					<key>name</key>
					<string>invalid.illegal.invalidchar.prolog</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-z]\w*.*:-)</string>
			<key>end</key>
			<string>\.</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.rule.end.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[a-z]\w*.*:-)</string>
					<key>end</key>
					<string>(?=:-)</string>
					<key>name</key>
					<string>meta.rule.signature.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-z]\w*(?=\(|\s*:-)</string>
							<key>name</key>
							<string>entity.name.function.rule.prolog</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\()</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.rule.parameters.begin.prolog</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\))</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.rule.parameters.end.prolog</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.rule.parameters.prolog</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parameter</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>:-</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.definition.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\.)</string>
					<key>name</key>
					<string>meta.rule.definition.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expr</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>statement</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-z]\w*\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.statement.parameters.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.statement.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#builtins</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.begin.statement.parameters.prolog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.statement.parameters.prolog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.statement.prolog</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#basic_elem</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.prolog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.prolog</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.quote.prolog</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>name</key>
			<string>variable.other.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b_\b</string>
					<key>name</key>
					<string>variable.language.anonymous.prolog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Z_][a-zA-Z0-9_]*\b</string>
					<key>name</key>
					<string>variable.other.prolog</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.prolog</string>
	<key>uuid</key>
	<string>8F6F5A72-EB1A-4774-8053-37715C925860</string>
</dict>
</plist>
